# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'
require 'open-uri'
require 'tempfile'
require 'yaml'

Vagrant.require_version ">= 1.6.0"

$cpu_count = 2
$vm_memory = 4096

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.hostname = "vagrant-box.local"
  config.vm.network :private_network, ip: "192.168.56.101"
  config.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

  config.vm.provider :virtualbox do |v|
    # vb.name = ubuntu
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", $vm_memory]
    v.customize ["modifyvm", :id, "--name", "vagrant-box.local"]
    v.cpus = $cpu_count
  end

  config.vm.provision "shell", path: "provision/setup.sh"
  config.vm.provision "shell", path: "provision/validate.sh"
  config.vm.provision "shell", path: "provision/git_repo.sh"
  config.vm.provision "shell", path: "provision/container_bootup.sh"
end
